### ISSUE TITLE
What linux is best for strictly-netbeans

### ISSUE THREAD

**Issue by bgold04** [jgneff/strictly-netbeans#1]
The detailed description I am having with my RHEL8 netbeans compile of a 2020 github GPL-3 repo is here: https://stackoverflow.com/questions/78775164/what-linux-os-will-permit-netbeans-to-update-a-currently-non-functional-java-app

I would surely be helped if I knew what flavor of linux strictly-netbeans and its related snaps works best on.

**Comment by jgneff** [comment]
I have not tested the profiler with the Strictly NetBeans Snap package, and it looks as if it's not going to work. The native libraries for the NetBeans profiler require GLIBC version 2.34, yet the latest GLIBC in the Strictly NetBeans Snap package is version 2.27.

Below are the GLIBC versions required by the shared library that the profiler is trying to load:

```console
$ objdump \
  --dynamic-syms \
  /snap/strictly-netbeans/current/netbeans/profiler/lib/deployed/jdk16/linux-amd64/libprofilerinterface.so \
  | grep GLIBC | sed 's/^.* (\(GLIBC_*[\.0-9]*\)) .*/\1/' | sort --unique --version-sort
GLIBC_2.2.5
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.14
GLIBC_2.34
```

And below is the GLIBC library in the `core18` package used by the Strictly NetBeans Snap package:

```console
$ grep libc6 /snap/core18/current/snap/manifest.yaml 
    - libc6-dev=2.27-3ubuntu1.6+esm3
    - libc6=2.27-3ubuntu1.6+esm3
```

I'm not sure whether there's a way to get the profiler working in the Snap package. Perhaps I could upgrade to the `core20` support package, but that might cause compatibility problems with the Strictly Maven and OpenJDK Snap packages to which it connects.

I recommend that you download the unconfined [official release of NetBeans](https://netbeans.apache.org/front/main/download/nb22/) from the Apache website and run on any version of Linux that has GLIBC 2.34 or later. You can find the list for Ubuntu and Fedora in the [README file](https://github.com/jgneff/openjdk?tab=readme-ov-file#ubuntu) of the OpenJDK Snap package.

You could also install the official [NetBeans Snap package](https://snapcraft.io/netbeans), which runs unconfined in *classic* mode using your local system libraries.

Are you installing the Strictly NetBeans Snap package for its security benefits, or for some other reason?

**Comment by bgold04** [comment]
It is much harder to compile and run this JavaFX code than in 2022.  Apparently, I need better gtk pointers, access to GLIBC, maven, ant, openjdk, javafx-sdk, and perhaps some web services that have been deprecated.  I thought strictly-netbeans would solve some of these problems and improve debugging.  I had already tried off-the-shelf netbeans, which provided many of the same problems.  Maybe I have to go backward in netbean editions.  In 2022 the compile was smooth, bugless and provided a fine app!

**Comment by jgneff** [comment]
If you're just trying to build the JavaFX application, I'm surprised that the NetBeans Profiler was invoked. In my experience, that is run manually to profile the performance of the running application.

I haven't seen the problems you're having with my own JavaFX applications in NetBeans. You might try starting with something simple like my "Hello, World" JavaFX project called [hello-javafx](https://github.com/jgneff/hello-javafx) to see whether you can build it in NetBeans using Maven. If that works, perhaps you can use it as a guide to simply your application's build process.
